config/routes.rb
Rails.application.routes.draw do
  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'
  
  get 'downgrade' => 'charges#downgrade'
  
  resources :charges, only: [:new, :create]
  resources :collaborators, only: [:create, :destroy]

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators
  has_many :collaborating_users, through: :collaborators, source: :wikis
  has_many :wikis
  
  after_initialize { self.role ||=  :standard }
  
  enum role: [:standard, :premium, :admin]
  
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborating_users, through: :collaborators, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
 def create
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   charge = Stripe::Charge.create(
     customer: customer.id,
     amount: 5_00,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )
   current_user.premium!
   flash[:notice] = "#{current_user.email}, enjoy your premium membership!"
   redirect_to user_path(current_user)
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end
 
 def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: 5_00
   }
 end
 
 def downgrade
    current_user.standard!
    current_user.wikis.update_all(private: false)
    flash[:notice] = "You are now downgraded to a free account."
     redirect_to root_path
 end
 
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    def create
        wiki = Wiki.find(params[:wiki_id])
        user = User.find(params[:user_id])
        

        Collaborator.create(user_id: user.id, wiki_id: wiki.id)
            
        if Collaborator.create(user_id: user.id, wiki_id: wiki.id)
               flash[:notice] = "#{user.email} is now a collaborator."
        end
        redirect_to edit_wiki_path(wiki)
    end
    
    def destroy
        wiki = Wiki.find(params[:wiki_id])
        user = User.find(params[:user_id])
        
        if wiki.collaborating_users.destroy(user)
            flash[:notice] = "#{user.email} was removed successfully."
        else
            flash.now[:alert] = 'There was a problem removing the user.'
        end
        redirect_to edit_wiki_path(wiki)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include WikisHelper
  
  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = params[:wiki][:user]
    
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = params[:wiki][:user]
    
    if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the Wiki. Please try again."
       render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_to_delete?
        current_user && current_user.admin?
    end
    
    def user_is_authorized_to_create_private_post?
        current_user.premium? || current_user.admin?
    end
    
    def markdown(text)
     extensions = {
       tables:                       true,
       fenced_code_blocks:           true,
       autolink:                     true,
       disable_indented_code_blocks: true,
       strikethrough:                true,
       superscript:                  true,
       underline:                    true,
       highlight:                    true,
       quote:                        true,
       footnotes:                    true
     }
 
     renderer = Redcarpet::Render::HTML
     markdown = Redcarpet::Markdown.new(renderer, extensions)
 
     markdown.render(text).html_safe
   end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Pay and upgrade!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <li><%= link_to "About", about_path %></li>
        <div class="pull-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
      
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

      <%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Blocipedia</h1>
<h4>Create and Share Markdown Wikis</h4>
<br>
<br>
<% if current_user.standard? || current_user.admin? %>
    <div>
        <%= link_to 'UPGRADE', new_charge_path %> to Premium account and create private Wikis
    </div>
<% end %>
<% if current_user.premium? || current_user.admin? %>
    <div>
        <%= link_to 'DOWNGRADE', downgrade_path, data: {confirm: 'Confirm downgrade and lose access to create private Wikis. Private Wikis will become public.'} %> to Free account
    </div>
<% end %>

app/views/wikis/_collaborators.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Add</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @users = User.where.not(id: current_user.id) %>
    <% @users.each do |user| %>
      <tr>
        <td>Column content</td>
        <td><%= user.email %></td>
        <td><%= link_to ' ', collaborators_path(user_id: user.id, wiki_id: wiki.id), method: :post, class: 'btn btn-success glyphicon glyphicon-ok' %></td>
        <td><%= link_to ' ', collaborators_path(user_id: user.id, wiki_id: wiki.id), method: :delete, class: 'btn btn-danger glyphicon glyphicon-remove' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
           <%= f.label :title %>
           <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
       </div>
       <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: "Enter body" %>
            <small>Styling with Markdown is supported</small>
        </div>
        <% if user_is_authorized_to_create_private_post? %>
            <div class="form-group">
               <%= f.label :private, class: 'checkbox' do %>
                   <%= f.check_box :private %> Private Topic
               <% end %>
            </div>
        <% end %>
        <div class="form-group">
             <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <div class="panel panel-primary">
         <div class="panel-heading">
           <h3 class="panel-title">Collaborators</h3>
         </div>
         <div class="panel-body">
           <%= render partial: "collaborators", locals: { wiki: @wiki }  %>
         </div>
        </div>
     <% end %>
 </div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<div class="col-md-4 pull-right">
     <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>
<% if user_is_authorized_to_create_private_post? %>
 <% @wikis.each do |wiki| %>
   <div class="media">
    <div class="media-body">
     <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
     </h4>
    </div>
   </div>
 <% end %>
 <% else %>
 <% @wikis.each do |wiki| %>
  <% if not wiki.private?%>
   <div class="media">
    <div class="media-body">
     <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
     </h4>
    </div>
   </div>
  <% end %>
 <% end %>
<% end %>

app/views/wikis/new.html.erb
<%= form_for @wiki do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: "Enter body" %>
    </div>
    <% if user_is_authorized_to_create_private_post? %>
    <div class="form-group">
       <%= f.label :private, class: 'checkbox' do %>
           <%= f.check_box :private %> Private Topic
       <% end %>
    </div>
    <% end %>
 
    <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
   </div>

    <div class="col-md-4">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% if user_is_authorized_to_delete? %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
      <% end %>    
    </div>

 </div>